### ISSUE TITLE
 Inquiry about the Performance and Running Speed of the Algorithm in AV-Solutions/streampetr-trt

### ISSUE THREAD

**Issue by steinate** [NVIDIA/DL4AGX#54]
Hello, I appreciate your contribution on the code to execute the StreamPETR C++ application using TensorRT on the NVIDIA Drive Orin platform. I'm curious to learn about the performance of the algorithm on the NVIDIA Drive Orin platform. Could you please provide details on the processing speed, specifically the number of frames it can process per second?

**Comment by kminoda** [comment]
@steinate I am curious about the results. Do you have any reference value that you can share with us? Thanks!
