### ISSUE TITLE
Can't find mmdet3d when training UniAD-tiny

### ISSUE THREAD

**Issue by riceXX** [NVIDIA/DL4AGX#64]
Hi,
I'm trying to cover UniAD to onnx.
I followed the steps:Project setup for deployment,Environments Preparation,Data Preparation.when training the UniAD-tiny model,  I get an error ahout mmdet3d.

`./tools/uniad_dist_train.sh ./projects/configs/stage1_track_map/tiny_imgx0.25_track_map.py 1`

> Traceback (most recent call last):
>   File "./tools/train.py", line 17, in <module>
>     from mmdet3d import __version__ as mmdet3d_version
> ModuleNotFoundError: No module named 'mmdet3d'
> 

I try to import uniad_mmdets3,but it still not work.

> Traceback (most recent call last):
>   File "./tools/train.py", line 21, in <module>
>     from uniad_mmdet3d import __version__ as mmdet3d_version
>   File "/workspace/UniAD/third_party/uniad_mmdet3d/__init__.py", line 1, in <module>
>     from .apis.train import custom_train_model
>   File "/workspace/UniAD/third_party/uniad_mmdet3d/apis/train.py", line 7, in <module>
>     from .mmdet_train import custom_train_detector
>   File "/workspace/UniAD/third_party/uniad_mmdet3d/apis/mmdet_train.py", line 31, in <module>
>     from ..datasets.builder import build_dataloader, custom_build_dataset
>   File "/workspace/UniAD/third_party/uniad_mmdet3d/datasets/__init__.py", line 1, in <module>
>     from .pipelines import *
>   File "/workspace/UniAD/third_party/uniad_mmdet3d/datasets/pipelines/__init__.py", line 4, in <module>
>     from .formating import Collect3D, DefaultFormatBundle, DefaultFormatBundle3D
>   File "/workspace/UniAD/third_party/uniad_mmdet3d/datasets/pipelines/formating.py", line 91, in <module>
>     class Collect3D(object):
>   File "/mmcv/mmcv/utils/registry.py", line 315, in _register
>     self._register_module(
>   File "/mmcv/mmcv/utils/registry.py", line 249, in _register_module
>     raise KeyError(f'{name} is already registered '
> KeyError: 'Collect3D is already registered in pipeline'

I try to train in the enviroment of https://github.com/OpenDriveLab/UniAD,but I get another error about mmdet3d.

> File "./tools/train.py", line 260, in <module>
>     main()
>   File "./tools/train.py", line 127, in main
>     plg_lib = importlib.import_module(_module_path)
>   File "/home/xx/anaconda3/envs/uniad/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/xx/DL4AGX/AV-Solutions/uniad-trt/UniAD/projects/mmdet3d_plugin/__init__.py", line 2, in <module>
>     from .core.bbox.coders.nms_free_coder import NMSFreeCoder
>   File "/home/xx/DL4AGX/AV-Solutions/uniad-trt/UniAD/projects/mmdet3d_plugin/core/bbox/coders/__init__.py", line 2, in <module>
>     from .detr3d_track_coder import DETRTrack3DCoder
>   File "/home/xx/DL4AGX/AV-Solutions/uniad-trt/UniAD/projects/mmdet3d_plugin/core/bbox/coders/detr3d_track_coder.py", line 8, in <module>
>     from third_party.uniad_mmdet3d.core.bbox import xywhr2xyxyr
>   File "/home/xx/DL4AGX/AV-Solutions/uniad-trt/UniAD/third_party/uniad_mmdet3d/__init__.py", line 1, in <module>
>     from .apis.train import custom_train_model
>   File "/home/xx/DL4AGX/AV-Solutions/uniad-trt/UniAD/third_party/uniad_mmdet3d/apis/train.py", line 7, in <module>
>     from .mmdet_train import custom_train_detector
>   File "/home/xx/DL4AGX/AV-Solutions/uniad-trt/UniAD/third_party/uniad_mmdet3d/apis/mmdet_train.py", line 31, in <module>
>     from ..datasets.builder import build_dataloader, custom_build_dataset
>   File "/home/xx/DL4AGX/AV-Solutions/uniad-trt/UniAD/third_party/uniad_mmdet3d/datasets/__init__.py", line 1, in <module>
>     from .pipelines import *
>   File "/home/xx/DL4AGX/AV-Solutions/uniad-trt/UniAD/third_party/uniad_mmdet3d/datasets/pipelines/__init__.py", line 3, in <module>
>     from .dbsampler import DataBaseSampler
>   File "/home/xx/DL4AGX/AV-Solutions/uniad-trt/UniAD/third_party/uniad_mmdet3d/datasets/pipelines/dbsampler.py", line 7, in <module>
>     from third_party.uniad_mmdet3d.core.bbox import box_np_ops
>   File "/home/xx/DL4AGX/AV-Solutions/uniad-trt/UniAD/third_party/uniad_mmdet3d/core/bbox/__init__.py", line 1, in <module>
>     from .coders import *
>   File "/home/xx/DL4AGX/AV-Solutions/uniad-trt/UniAD/third_party/uniad_mmdet3d/core/bbox/coders/__init__.py", line 2, in <module>
>     from .centerpoint_bbox_coders import CenterPointBBoxCoder
>   File "/home/xx/DL4AGX/AV-Solutions/uniad-trt/UniAD/third_party/uniad_mmdet3d/core/bbox/coders/centerpoint_bbox_coders.py", line 9, in <module>
>     class CenterPointBBoxCoder(BaseBBoxCoder):
>   File "/home/xx/anaconda3/envs/uniad/lib/python3.8/site-packages/mmcv/utils/registry.py", line 311, in _register
>     self._register_module(
>   File "/home/xx/anaconda3/envs/uniad/lib/python3.8/site-packages/mmcv/utils/registry.py", line 246, in _register_module
>     raise KeyError(f'{name} is already registered '
> KeyError: 'CenterPointBBoxCoder is already registered in bbox_coder'
> 

Are there additional steps or requirements in the training? Does it need to install mmdetsd in docker?I'm not sure about this issue.
Thanks!

**Comment by DeepBehavier** [comment]
same problem

**Comment by riceXX** [comment]
When training tiny-UniAD, I am trying to use official UniAD，but replace the Configs.

在 2024-11-12 16:36:41，DeepBehavier ***@***.***> 写道：


same problem

**Comment by Jian-danai** [comment]
We recently updated the documentation to give detailed training instructions, please `git pull` to update and check out [here](https://github.com/NVIDIA/DL4AGX/blob/master/AV-Solutions/uniad-trt/documents/train_export.md).
