### ISSUE TITLE
where to download  `TensorRT 8.6.13.3` for NVIDIA DRIVE Orin platform

### ISSUE THREAD

**Issue by DeepBehavier** [NVIDIA/DL4AGX#65]
Thanks for the excellent work.  I test the inference code with tensorrt 8.6.1 on 3090. But we met some problem( core dumped)
I can't find tensorrt 8.6.13.3.
where to download tensorrt 8.6.13.3?

**Comment by Jian-danai** [comment]
You can download "DRIVE OS [DRIVE AGX Orin Latest]" from https://developer.nvidia.com/drive/downloads
It contains TensorRT-8.6.13

**Comment by DeepBehavier** [comment]
thank you very much for your help

**Comment by DeepBehavier** [comment]
thank you very much for your help. Since I use orin development board, can I install drive os？Looking forward to your reply

> You can download "DRIVE OS [DRIVE AGX Orin Latest]" from https://developer.nvidia.com/drive/downloads It contains TensorRT-8.6.13
> 
> If not possible to use or download the above, later you may try our latest TensorRT-10.6 from https://developer.nvidia.com/tensorrt/download/10x We will update tensorrt plugins to support trt-10 in the near future.

**Comment by Jian-danai** [comment]
@DeepBehavier do you mean you are not using Orin?

**Comment by Jian-danai** [comment]
Do you have an [NV-Developer account](https://developer.nvidia.com/drive/agx-sdk-program) by any means?
If not, please wait for our support for TensorRT-10 on x86 in coming weeks.
